# Generated by Django 3.2.5 on 2021-11-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='real_name',
            new_name='name',
        ),
    ]
