# Generated by Django 3.2.5 on 2021-11-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_item_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='student',
        ),
    ]
