# Generated by Django 3.2.8 on 2021-10-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_item_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='point_used',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
