# Generated by Django 3.2.7 on 2021-11-16 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20211112_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.student'),
        ),
    ]
