# Generated by Django 3.2.8 on 2021-10-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_student_point_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_count',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Payments_count',
            new_name='pay_count',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_price',
            new_name='price',
        ),
    ]
