# Generated by Django 3.2.5 on 2021-11-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_rename_owner_item_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='real_name',
            field=models.CharField(max_length=70),
        ),
    ]
