# Generated by Django 3.2.8 on 2021-10-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_rename_pay_count_item_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('payment', models.IntegerField()),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='action',
        ),
        migrations.RemoveField(
            model_name='item',
            name='number',
        ),
    ]
