# Generated by Django 3.2.8 on 2021-10-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_alter_observe_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observe',
            name='check',
            field=models.CharField(choices=[('X', '미확인'), ('O', '확인')], max_length=20),
        ),
    ]
