# Generated by Django 3.2.8 on 2021-10-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_alter_observe_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='observe',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
