# Generated by Django 3.2.8 on 2021-10-31 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_alter_observe_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observe',
            name='check',
        ),
    ]
