# Generated by Django 3.2.8 on 2021-11-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_remove_observe_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='observe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
