# Generated by Django 3.2.8 on 2021-11-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_observe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='observe',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
