# Generated by Django 3.2.8 on 2021-11-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_observe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observe',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
